Spring:
  datasource:
    url: postgres://fl0user:${sqlPassword}@ep-orange-smoke-a5nqcxq3.us-east-2.aws.neon.fl0.io:5432/logify?sslmode=require
    username: fl0user
    password: ${sqlPassword}
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: mysql
